const customizedTexts={
    title: `❤️ Damla & Kerem ❤️ `,
    image:`assets/images/damker.jpeg`,
    description:`Doğum günün kutlu olsun nice mutlu bizli senelere❤️ `,
    clip:`assets/videos/video.mp4`
}
const sentences = [
    "Gülüşünü seviyorum ❤️",
    "Beni hep düşündüğün için ❤️",
    "Sarılmaların huzur veriyor ❤️",
    "Çok tatlısın ❤️",
    "Birlikte kahve içmeyi seviyorum ❤️",
    "Yüzüne bakınca içim ısınıyor ❤️",
    "Yanındayken zaman duruyor ❤️",
    "Beraber her şey daha güzel ❤️",
    "Seninle çok eğleniyorum ❤️",
    "Her şeyinle seni seviyorum ❤️",
    "Sabah mesajlarınla güne güzel başlıyorum ❤️",
    "Kahkahalarını duyunca ben de gülüyorum ❤️",
    "Zor zamanlarda yanımda olduğun için teşekkür ederim ❤️",
    "Beni olduğum gibi seviyorsun ❤️",
    "Ellerin ellerime çok yakışıyor ❤️",
    "Sana baktıkça içim kıpır kıpır oluyor ❤️",
    "Beraber hayal kurmayı seviyorum ❤️",
    "Her gün sana biraz daha aşık oluyorum ❤️",
    "Küçük sürprizlerini çok seviyorum ❤️",
    "Seni düşünmek bile yüzümü güldürüyor ❤️",
    "Konuşmadan bile anlaşabiliyoruz ❤️",
    "Uyurken yüzüne bakmak en sevdiğim şeylerden biri ❤️",
    "Seninle gelecek çok güzel olacak ❤️",
    "İyi ki hayatımdasın, iyi ki varsın ❤️",
    "Sen benim en güzel tesadüfümsün ❤️",
    "Sana sarılmak en güvenli yer gibi ❤️",
    "Kıskanmam bile seni ne kadar çok sevdiğimin göstergesi ❤️",
    "Sana olan sevgim sonsuzluk gibi ❤️",
    "Birlikte yaşadığımız anılar kalbimde bir hazine ❤️",
    "Sadece sevgilim değil, en yakın dostumsun da ❤️",
    "Gözlerine her bakışta kayboluyorum ❤️",
    "Beni her halimle kabulleniyorsun ❤️",
    "En kötü günümde bile yüzümü güldürebiliyorsun ❤️",
    "Yolda yürürken bile elini tutmak istiyorum ❤️",
    "Geleceğimde sen olduğun sürece korkmuyorum ❤️",
    "Sana her gün yeniden aşık oluyorum ❤️"
];